version: '3'
services:
  db:
    image: mariadb:10.5
    container_name: "mysql"
    restart: always
    environment:
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=123
    ports:
      - "3308:3306"
    volumes:
      - ./config/tarefa.sql:/docker-entrypoint-initdb.d/tarefa.sql

  adminer:
    image: adminer:4.8.1
    container_name: "adminer"
    restart: always
    ports:
      - 8080:8080